In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

# Agricultural dataset
data={"Rainfall":[200,180,150,120,100,80],
      "Fertilizer":[50,40,35,30,20,15],
      "Temperature":[30,28,27,25,24,23],
      "Yield":[1,1,1,0,0,0]}
df=pd.DataFrame(data)

# Features
X=df[["Rainfall","Fertilizer","Temperature"]]

# target
y=df["Yield"]

# split data set
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.3, random_state=42)


#Create model
model=LogisticRegression()

# train model
model.fit(X_train,y_train)

# prediction
y_pred=model.predict(X_test)

# evaluation
print("Accuracy:",accuracy_score(y_test,y_pred))
print("\n Confusion matrix:\n", confusion_matrix(y_test,y_pred))
print("\n Classification report\n",classification_report(y_test,y_pred))

# model coefficients
print("\n Intercept:",model.intercept_)
print("Coefficients:",model.coef_)

Accuracy: 1.0

 Confusion matrix:
 [[2]]

 Classification report
               precision    recall  f1-score   support

           1       1.00      1.00      1.00         2

    accuracy                           1.00         2
   macro avg       1.00      1.00      1.00         2
weighted avg       1.00      1.00      1.00         2


 Intercept: [-42.28601861]
Coefficients: [[0.29744553 0.04968041 0.019827  ]]


/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:407: UserWarning: A single label was found in 'y_true' and 'y_pred'. For the confusion matrix to have the correct shape, use the 'labels' parameter to pass all known labels.
  warnings.warn(


seperate execution


In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report


In [ ]:
# Agricultural dataset
data={
    "Rainfall":[200,180,150,120,100,80],
    "Fertilizer":[50,40,35,30,20,15],
    "Temperature":[30,28,27,25,24,23],
    "Yield":[1,1,1,0,0,0]
}
df=pd.DataFrame(data)
display(df)

In [ ]:
# Features
X=df[["Rainfall","Fertilizer","Temperature"]]

# target
y=df["Yield"]
display(X.head())
display(y.head())

In [ ]:
# split data set
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.3, random_state=42)
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

In [ ]:
#Create model
model=LogisticRegression()

# train model
model.fit(X_train,y_train)

In [4]:
# prediction
y_pred=model.predict(X_test)
print("Predicted values for y_test:", y_pred)
print("Actual values for y_test:", y_test.values)

Predicted values for y_test: [1 1]
Actual values for y_test: [1 1]


In [14]:
# evaluation
print("Accuracy:",accuracy_score(y_test,y_pred))
print("\n Confusion matrix:\n", confusion_matrix(y_test,y_pred))
print("\n Classification report\n",classification_report(y_test,y_pred))

Accuracy: 1.0

 Confusion matrix:
 [[2 0]
 [0 1]]

 Classification report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3



In [6]:
# model coefficients
print("\n Intercept:",model.intercept_)
print("Coefficients:",model.coef_)


 Intercept: [-42.28601861]
Coefficients: [[0.29744553 0.04968041 0.019827  ]]


In [13]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

# Agricultural dataset
data={"Rainfall":[200,180,150,120,100,80,120,130,140],
      "Fertilizer":[50,40,35,30,20,15,40,20,30],
      "Temperature":[30,28,27,25,24,23,22,23,30],
      "Yield":[1,1,1,0,0,0,1,0,1]}
df=pd.DataFrame(data)

# Features
X=df[["Rainfall","Fertilizer","Temperature"]]

# target
y=df["Yield"]

# split data set
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=0.3, random_state=42)


#Create model
model=LogisticRegression()

# train model
model.fit(X_train,y_train)

# prediction
y_pred=model.predict(X_test)
print("predicted values",y_pred)
print("actual y values",y_test.values)

# evaluation

print("Accuracy:",accuracy_score(y_test,y_pred))
print("\n Confusion matrix:\n", confusion_matrix(y_test,y_pred))
print("\n Classification report\n",classification_report(y_test,y_pred))

# model coefficients
print("\n Intercept:",model.intercept_)
print("Coefficients:",model.coef_)

predicted values [0 1 0]
actual y values [0 1 0]
Accuracy: 1.0

 Confusion matrix:
 [[2 0]
 [0 1]]

 Classification report
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         1

    accuracy                           1.00         3
   macro avg       1.00      1.00      1.00         3
weighted avg       1.00      1.00      1.00         3


 Intercept: [-58.45511227]
Coefficients: [[ 0.34873383  0.52640456 -0.07084592]]


In [11]:
print('Printing y_test as a pandas Series:')
print(y_test)

Printing y_test as a pandas Series:
8    1
1    1
5    0
Name: Yield, dtype: int64


In [12]:
print('\nPrinting y_test as a NumPy array (using .values):')
print(y_test.values)


Printing y_test as a NumPy array (using .values):
[1 1 0]
