In [3]:
import numpy as np
# Nutrient requirement for 3 crops
# Rows: crops("wheat,maize,rice")
#columns:nutrients(npk)
nutrient_needs=np.array([[120,60,80],[150,75,100],[100,50,70]])


# available fertilizer composition (%npk)
# rows:fert types
#columns nutrient content
fertilizer_composition=np.array([[0.20,0.10,0.15],  # 20%n,10%p and 15% k
 [0.15,0.20,0.10],
  [0.10,0.15,0.25]])

print("\n Nutrient requirements(kg/ha):")
print(nutrient_needs)
print("\n Fertilizer composition(%):")
print(fertilizer_composition)


# matrix transposable element
print("\n Transposed nutrient needs(Nutrient *crops):")
print(nutrient_needs.T)

# calculate felt amount
total_nutrient_per_crop=np.sum(nutrient_needs,axis=1)
print(f"Nutrint required by each crop:{total_nutrient_per_crop} kg/ha")


# matrix multiplication: total nutrint delivery
# if we applay 100 kg of each fertilizer type
fertilizer_application=np.array([100,100,100]) #kg of each type
nutrients_delivered=np.dot(fertilizer_application,fertilizer_composition)
print(f"\n Nutrients from 100 kg of each fertilizer:{nutrients_delivered}")

# calculate determinant( for checking if matric is invertible)

det=np.linalg.det(fertilizer_composition)
print(f"Determinant of fertilizer matrix:{det:.6f}")


# identity matrix exmaple (scalar factor)
scaling=np.eye(3)*1.1  # 10 percent increase
enhanced_needs=np.dot(nutrient_needs,scaling)
print("Enhanced nutrinet needs(10percent increase):")
print(enhanced_needs)



 Nutrient requirements(kg/ha):
[[120  60  80]
 [150  75 100]
 [100  50  70]]

 Fertilizer composition(%):
[[0.2  0.1  0.15]
 [0.15 0.2  0.1 ]
 [0.1  0.15 0.25]]

 Transposed nutrient needs(Nutrient *crops):
[[120 150 100]
 [ 60  75  50]
 [ 80 100  70]]
Nutrint required by each crop:[260 325 220] kg/ha

 Nutrients from 100 kg of each fertilizer:[45. 45. 50.]
Determinant of fertilizer matrix:0.004625
Enhanced nutrinet needs(10percent increase):
[[132.   66.   88. ]
 [165.   82.5 110. ]
 [110.   55.   77. ]]
