In [ ]:
import numpy as np
arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array((1,3.5,3,3,5))
print(arr)
print(type(arr))

[1.  3.5 3.  3.  5. ]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
arr=np.array(42)
print(arr)


42


In [ ]:
import numpy
arr=numpy.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
# 2d arrays
import numpy as np
a=[[1,2,5],[3,4,6]]
arr=np.array(a)
print(arr)

[[1 2 5]
 [3 4 6]]


In [ ]:
# 3d arrays
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#high dimensional array
import numpy as np
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim," number of dimensions")

[[[[[1 2 3 4]]]]]
5  number of dimensions


In [ ]:
arr=np.array([1,2,3,4])
print(arr[[0]])
print(arr[[0,2,3]])
print((arr[0]+arr[2]))

[1]
[1 3 4]
4


In [ ]:
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr[[0,1]])
print(arr[0,1])

[[1 2 3 4]
 [5 6 7 8]]
2


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr)
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:
# usinf built in functions

zeros=np.zeros((3,4))
ones=np.ones((2,3))
range=np.arange(0,10,2)
linspace=np.linspace(0,1,5)
identify=np.eye(3)
random_arr=np.random.rand(3,4)
print("\n")
print(zeros)
print("\n")
print(ones)
print("\n")
print(range)
print("\n")
print(linspace)
print("\n")
print(identify)
print("\n")
print(random_arr)



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1.]
 [1. 1. 1.]]


[0 2 4 6 8]


[0.   0.25 0.5  0.75 1.  ]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


[[0.2067656  0.23732802 0.99512365 0.58289728]
 [0.68925883 0.80782295 0.28767707 0.69218322]
 [0.20318511 0.74021191 0.23179279 0.78967525]]


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr[1:3])

[2 3]


In [ ]:
arr=np.array([[1,2],[3,4],[5,6],[7,8]])
print(arr[1:])

[[3 4]
 [5 6]
 [7 8]]


In [ ]:
# datatypes of element
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)



(2, 3)


In [ ]:
# to get total number of elemnts
print(a.size)
# to get type
print(a.dtype)
print(type(a))
# to get how many number of dimensions
print(a.ndim)

6
int64
<class 'numpy.ndarray'>
2


In [ ]:
# statistical analysis
b=np.sum(a)
print(b)

21


In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))
print(np.max(a))
print(np.min(a))
b=np.array([[10,50,30],[20,70,90]])
print(np.argmax(b))

[2.5 3.5 4.5]
[2. 5.]
6
1
5


In [ ]:
# agricultural analysis operation
# crop yields of 4 crops over 5 season
crop_yields=np.array([[12.5,13.2,14.1,13.8,15.2],[10.3,11.5,10.8,12.1,11.9],[15.1,14.8,16.2,15.5,16.8],[11.2,10.9,12.3,11.7,12.8]])
print("crop yield array(ton)")
print(crop_yields)
print(f"\nShape:{crop_yields.shape}")
print(f"Data type:{crop_yields.dtype}")
print(f"Total elements:{crop_yields.size}")
print(f"number of dimensions:{crop_yields.ndim}")

# agricultural analysis operation
total_yield=np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1)
avg_yield_per_season=np.mean(crop_yields,axis=0)
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)

print(f"Total production:{total_yield}")
print(f"Average yield per farm:{avg_yield_per_farm}")
print(f"Average yield per season:{avg_yield_per_season}")
print(f"maximun yield:{max_yield}")
print(f"minimum yield:{min_yield}")

#best cropping pattern
best_farm=np.argmax(avg_yield_per_farm)
print(f"\nBest performing farm: Farm{best_farm+1}")
print(f"Their average yield:{avg_yield_per_farm[best_farm]:.2f} tons")


crop yield array(ton)
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

Shape:(4, 5)
Data type:float64
Total elements:20
number of dimensions:2
Total production:262.7
Average yield per farm:[13.76 11.32 15.68 11.78]
Average yield per season:[12.275 12.6   13.35  13.275 14.175]
maximun yield:16.8
minimum yield:10.3

Best performing farm: Farm3
Their average yield:15.68 tons


In [ ]:
# agricultural analysis operation
# crop yields of 4 crops over 5 season
crop_yields=np.array([[12.5,13.2,14.1,13.8,15.2],[10.3,11.5,10.8,12.1,11.9],[15.1,14.8,16.2,15.5,16.8],[11.2,10.9,12.3,11.7,12.8]])
print("crop yield array(ton)")
print(crop_yields)
print(f"\nShape:{crop_yields.shape}")
print(f"Data type:{crop_yields.dtype}")
print(f"Total elements:{crop_yields.size}")
print(f"number of dimensions:{crop_yields.ndim}")

# agricultural analysis operation
total_yield=np.sum(crop_yields)
avg_yield_per_farm=np.mean(crop_yields,axis=1)
avg_yield_per_season=np.mean(crop_yields,axis=0)
max_yield=np.max(crop_yields)
min_yield=np.min(crop_yields)

print("Total production:",total_yield)
print("Average yield per farm",avg_yield_per_farm)
print("Average yield per season",avg_yield_per_season)
print("maximun yield:",max_yield)
print(f"minimum yield:",min_yield)

#best cropping pattern
best_farm=np.argmax(avg_yield_per_farm)
print(f"\nBest performing farm: Farm{best_farm+1}")
print(f"Their average yield:{avg_yield_per_farm[best_farm]:.2f} tons")


crop yield array(ton)
[[12.5 13.2 14.1 13.8 15.2]
 [10.3 11.5 10.8 12.1 11.9]
 [15.1 14.8 16.2 15.5 16.8]
 [11.2 10.9 12.3 11.7 12.8]]

Shape:(4, 5)
Data type:float64
Total elements:20
number of dimensions:2
Total production: 262.7
Average yield per farm [13.76 11.32 15.68 11.78]
Average yield per season [12.275 12.6   13.35  13.275 14.175]
maximun yield: 16.8
minimum yield: 10.3

Best performing farm: Farm3
Their average yield:15.68 tons


In [ ]:
import pandas as pd
a=np.array([[[1,2,3,4,5],[6,7,8,9,0]]])
print(a.ndim)

3


In [ ]:
a=[[[1,2],[3,4]],[[5,6],[7,8]]]
b=np.array(a)
print(b)
print(b.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [40]:
# sorting elements in an array
import numpy as np
arr=np.array([2,1,5,3,7,4,6,8])
print(arr)
np.sort(arr)
np.argsort(arr)



[2 1 5 3 7 4 6 8]


array([1, 0, 3, 5, 2, 6, 4, 7])

In [39]:
# numpy argsort
import numpy as np
x=np.array([3,1,2])
np.argsort(x)

array([1, 2, 0])

In [44]:
# concatenation
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(np.concatenate((a,b)))
c=a+b
print(c)

[1 2 3 4 5 6 7 8]
[ 6  8 10 12]


In [48]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6]])
print(np.concatenate((x,y),axis=0))

[[1 2]
 [3 4]
 [5 6]]


In [63]:
x=np.array([[1,2],[3,4]])
y=np.array([[5],[6]])
print(np.concatenate((x,y),axis=1))

[[1 2 5]
 [3 4 6]]


In [69]:
# arr.reshape()
a=np.arange(9)
print(a)
b=a.reshape(3,3)
print(b)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [74]:
# indexing and slicing
data=np.array([1,2,3,4])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-3:])

2
[1 2]
[2 3 4]
[2 3 4]


In [77]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a[a < 5])
print("\n")

five_up = (a >= 5)
print(a[five_up])
print("\n")

divisible_by_2 = a[a%2==0]
print(divisible_by_2)
print("\n")

c = a[(a > 2) & (a < 11)]
print(c)
print("\n")

five_up = (a > 5) | (a == 5)
print(five_up)

[1 2 3 4]


[ 5  6  7  8  9 10 11 12]


[ 2  4  6  8 10 12]


[ 3  4  5  6  7  8  9 10]


[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [79]:
#converting distance in miles to kilometers
data=np.array([1.0,2.0])
print(data*1.6)

[1.6 3.2]
