wrong answers



In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])

b=np.array([[10,20,30]])
print(a+b)

[[11 22 33]
 [14 25 36]]


In [ ]:
a=np.array([[1,2],[3,4],[5,6]])
mask=np.array([True,False,True])
c=a[mask]
print(c)

[[1 2]
 [5 6]]


In [ ]:
a=np.array([1,2,3])
b=a.reshape(3,)
print(b)

[1 2 3]


In [30]:
import numpy as np
x=np.arange(10)
# x[x%2==0]=x*2 this wont work because multiplication should be done to the selected elements only, not all elements
x[x%2==0]*=2 # here only selected i.e masked elements are multiplied by 2
print(x)


[ 0  1  4  3  8  5 12  7 16  9]


In [ ]:
x=np.arange(10)
x=x*(x%2==0)
print(x)

[0 0 2 0 4 0 6 0 8 0]


In [17]:
a= np.array([[1,2,4],[3,4,7],[5,6,8]])
print(a)
print(a[:,1])
print(a[:,[False,True,True]])

[[1 2 4]
 [3 4 7]
 [5 6 8]]
[2 4 6]
[[2 4]
 [4 7]
 [6 8]]


In [18]:
a=np.array([0.1,0.3,0.5,1,2])
print(a[a>0.5])

[1. 2.]


In [19]:
a=np.arange(1,7)
mask=np.array([True,False,True,False,True,False])
b=a[mask]*10
print(b)

[10 30 50]


In [24]:
a=np.array([[1,2],[3,4]])
b=np.array([[True,False],[False,True]])
print(a[b])

[1 4]


In [63]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[:,1])
print(a[:,[False,True]])

[2 4 6]
[[2]
 [4]
 [6]]


correct questions


In [27]:
a=np.array([10,20,30,40])
idx=np.array([3,0,3,1])
print(a[idx])

[40 10 40 20]


In [46]:
a=np.array([[1,2],[3,4],[5,6]])
print(a[a[:,1]%2==0])
print(a[a%2==0])
print(a[a[:,0]%2==0])
#print(a[:,a[1:,]%2==0]) this wont work"""

[[1 2]
 [3 4]
 [5 6]]
[2 4 6]
[]


In [43]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3]])
c=np.concatenate((a,b))
print(c)
print(a*b)

[[1 2 3]
 [4 5 6]
 [1 2 3]]
[[ 1  4  9]
 [ 4 10 18]]


In [48]:
a=np.array([1,2,3,4,5,6])
print(a)
a[a>3]=0
print(a)

[1 2 3 4 5 6]
[1 2 3 0 0 0]


In [53]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,0,1],[0,1,0]],dtype=bool)
print(a[b])

[1 3 5]


In [51]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,0,1],[0,1,0]])
print(a[b])

[[[4 5 6]
  [1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]
  [1 2 3]]]


In [58]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[1,2,3]])
print(a+b)

[[2 4 6]
 [5 7 9]]


In [73]:
a=np.arange(10)
a.reshape(10,)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a=np.array([[1,2,10,11],[3,4,12,13],[5,6,14,15],[7,8,16,17]])
print(a[:,3])
print(a[3])

[11 13 15 17]
[ 7  8 16 17]


In [87]:
a=np.array([1,2,3,4,5])
b=np.sum(a[1:3])
c=np.cumsum(a[1:3])
print(b)
print(c)

5
[2 5]


In [96]:
a=np.array([[1,2],[3,4]]).reshape(4,)

print(a)
print(a.shape)

[1 2 3 4]
(4,)


In [97]:
a=np.array([[1,2],[3,4]]).reshape(1,4)


print(a)
print(a.shape)

[[1 2 3 4]]
(1, 4)


In [100]:
a=np.array([[1,2],[3,4]])
print(a.shape)
b=np.array([1,2,3,4])
print(b.shape)
c=np.array([[1,2,3,4]])
print(c.shape)

(2, 2)
(4,)
(1, 4)


In [107]:
a=np.array([[1,2],[3,4]])
b=a.reshape(1,4)
c=a.reshape(4,)
print(a)
print(a.ndim)
print(b)
print(b.ndim)
print(c)
print(c.ndim)

[[1 2]
 [3 4]]
2
[[1 2 3 4]]
2
[1 2 3 4]
1
