In [24]:
import numpy as np
# Crop yields for 4 farms over 5years
yields=np.array([[45,48,52,49,53],
                [38,41,39,44,42],
                [52,55,58,56,60],
                [41,43,45,47,46]])
# weather impacts factor each year
weather_factors=np.array([1.0,0.95,1.05,0.98,1.02])
print("\n Original yields(tons/ha):")
print(yields)
print("\n Weather impact factors:",weather_factors)

print("[-2:-1]",yields[-2:-1])
print("[-2:]",yields[-2:])

# Broadcasting:adjust all farm yield
adjusted_yields=yields*weather_factors
print("\n Weather adjusted Years")
print(adjusted_yields.round(2))

# boolean indexing : find exceptional years
exceptional=adjusted_yields>55
print("\n Exceptional yields(>55):")
print(adjusted_yields[exceptional])
print(exceptional)

# conditional operation :classify yields
categories=np.where(
    adjusted_yields>50,"high",
    np.where(adjusted_yields>40,"medium","low")
)
print("\nyield categories")
print(categories)

# advanced indexing:select specific farm
selected_farms=[0,2]
print("\n Selected farms yields")
print(yields[selected_farms])

# multiconditioning filtering
good_years=adjusted_yields[(adjusted_yields>45)&(adjusted_yields<55)]
print("\n Good performing years(45-55tons):")
print(good_years)



 Original yields(tons/ha):
[[45 48 52 49 53]
 [38 41 39 44 42]
 [52 55 58 56 60]
 [41 43 45 47 46]]

 Weather impact factors: [1.   0.95 1.05 0.98 1.02]
[-2:-1] [[52 55 58 56 60]]
[-2:] [[52 55 58 56 60]
 [41 43 45 47 46]]

 Weather adjusted Years
[[45.   45.6  54.6  48.02 54.06]
 [38.   38.95 40.95 43.12 42.84]
 [52.   52.25 60.9  54.88 61.2 ]
 [41.   40.85 47.25 46.06 46.92]]

 Exceptional yields(>55):
[60.9 61.2]
[[False False False False False]
 [False False False False False]
 [False False  True False  True]
 [False False False False False]]

yield categories
[['medium' 'medium' 'high' 'medium' 'high']
 ['low' 'low' 'medium' 'medium' 'medium']
 ['high' 'high' 'high' 'high' 'high']
 ['medium' 'medium' 'medium' 'medium' 'medium']]

 Selected farms yields
[[45 48 52 49 53]
 [52 55 58 56 60]]

 Good performing years(45-55tons):
[45.6  54.6  48.02 54.06 52.   52.25 54.88 47.25 46.06 46.92]


In [7]:
yields=np.array([[45,48,52,49,53],
                [38,41,39,44,42],
                [52,55,58,56,60],
                [41,43,45,47,46]])
# weather impacts factor each year
weather_factors=np.array([1.0,0.95,1.05,0.98,1.02],
                         [1.0,2.0,1.1,1.2,1,3])
print(adjusted_yields=yields*weather_factors)

TypeError: Field elements must be 2- or 3-tuples, got '1.0'

In [35]:
import numpy as np
# create a 10*5 array with values 0-49
a=np.arange(50).reshape(10,5)
print("original array(10*5):")
print(a)

# select all the rows where the first feature(column0) id gretaer than 20
print(a[:])
print(a[:,0])
print(a[:,1])
selected_rows=a[a[:,0]>20]
print("\n Rows where first feature>20:\n",selected_rows)

original array(10*5):
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
[ 0  5 10 15 20 25 30 35 40 45]
[ 1  6 11 16 21 26 31 36 41 46]

 Rows where first feature>20:
 [[25 26 27 28 29]
 [30 31 32 33 34]
 [35 36 37 38 39]
 [40 41 42 43 44]
 [45 46 47 48 49]]
